### ISSUE TITLE
CLI application

### ISSUE THREAD

**Issue by lucor** [lucor/paw#3]
The main goal of Paw is to be GUI application, anyway a CLI application would be great :-)

**Comment by Jacalz** [comment]
This is a great idea. If the cli can avid using CGo, it should also be possible to more easily cross-compile it to a lot of operating systems and architectures.

**Comment by lucor** [comment]
At the moment there are no CGO dependencies. 
Still unsure if the CLI should be part of this project or be a dedicated one.
The latter would require a stable and public API.
In any case it would be great to use a CLI library with minimal third-party deps.

**Comment by lucor** [comment]
Added an first version in v0.15.0
