### ISSUE TITLE
Support showing website favicons

### ISSUE THREAD

**Issue by Jacalz** [lucor/paw#8]
### Is your feature request related to a problem? Please describe:

It is often faster to look for something visual (shapes, colours and so on) than to read the text.
Because of this, a lot of password manager allow showing the website favicons/icons for
login items.

### Is it possible to construct a solution with the existing API?

I believe so. Might require, or be good, to have some sort of caching so that favicons doesn't have to be downloaded from the websites every time the application loads. I don't know if just storing the cache unencrypted on disk is a good idea though, seems like an easy way for someone to read all the user's logins.

### Describe the solution you'd like to see:

Showing a favicon for the login item, instead of a generic website icon (if the website i question has one).

**Comment by lucor** [comment]
Thanks for reporting @Jacalz! 
Fully agree with this feature :) it was planned for the next release that should also improve the website item (i.e. make the website URI a link)
The resource should be encrypted as metadata field, and should fallback to the default if no favicon is available.

**Comment by lucor** [comment]
Added in v0.13.0
